### PR TITLE
F/layout manager

### PR DESCRIPTION
**Pull request by briand44**
This allows sitenow WYSIWYG to use the layout manager plugin in the ckeditor library. This can be tested by testing the pull request in https://github.com/ITS-UofIowa/sitenow_custom_profile/pull/92

### CODE REVIEW

**Comment by brandonneil** [comment]
I am planning to add some info to the README about what classes need to be added to the text format's Rules for Class Names section in addition to what Brian and I talked about regarding making `sitenow_wysiwyg_hide_outline_blocks` be `sitenow_wysiwyg_show_outline_blocks`

**Comment by brandonneil** [comment]
I made the changes outlined above for review. I'm going to look into supplying a PR to the ckeditor plugin.

**Comment by briand44** [comment]
These changes look good. I've tested it out and everything worked well for me. I like the trick of only allowing the medium breakpoint class.

**Comment by brandonneil** [comment]
Known issue: the ability to edit a layout to change it is broken. See https://github.com/radpet/ckeditor-layoutmanager/issues/13

**Pull request merged**
